add nomandb

diff --git a/.github/workflows/build-page.yml b/.github/workflows/build-page.yml
--- a/.github/workflows/build-page.yml
+++ b/.github/workflows/build-page.yml
@@ -69,10 +69,51 @@ jobs:
           fi
           echo "Graphviz installed successfully"
 
+  via_apt_install_no_mandb:
+    runs-on: ubuntu-24.04
+
+    steps:
+      - name: Disable man-db triggers
+        run: |
+          sudo dpkg-divert --local --rename --add /usr/bin/mandb
+          sudo ln -s /bin/true /usr/bin/mandb
+      - name: Install Graphviz via apt
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y graphviz
+      - name: Verify Graphviz installation
+        run: |
+          dot -vV
+          if ! command -v dot &> /dev/null; then
+            echo "Graphviz installation failed"
+            exit 1
+          fi
+          echo "Graphviz installed successfully"
+
   via_apt_install_without_update:
     runs-on: ubuntu-24.04
 
     steps:
+      - name: Install Graphviz via apt without update
+        run: |
+          sudo apt-get install -y graphviz
+      - name: Verify Graphviz installation
+        run: |
+          dot -vV
+          if ! command -v dot &> /dev/null; then
+            echo "Graphviz installation failed"
+            exit 1
+          fi
+          echo "Graphviz installed successfully"
+
+  via_apt_install_without_update_no_mandb:
+    runs-on: ubuntu-24.04
+
+    steps:
+      - name: Disable man-db triggers
+        run: |
+          sudo dpkg-divert --local --rename --add /usr/bin/mandb
+          sudo ln -s /bin/true /usr/bin/mandb
       - name: Install Graphviz via apt without update
         run: |
           sudo apt-get install -y graphviz
