add install via action without update

diff --git a/.github/workflows/build-page.yml b/.github/workflows/build-page.yml
--- a/.github/workflows/build-page.yml
+++ b/.github/workflows/build-page.yml
@@ -119,6 +119,48 @@ jobs:
           fi
           echo "Graphviz installed successfully"
 
+  via_action_no_update:
+    runs-on: ubuntu-24.04
+
+    steps:
+      - name: Install Graphviz via action
+        uses: ts-graphviz/setup-graphviz@v2
+        with:
+          ubuntu-skip-apt-update: true
+
+      - name: Verify Graphviz installation
+        run: |
+          dot -vV
+          if ! command -v dot &> /dev/null; then
+            echo "Graphviz installation failed"
+            exit 1
+          fi
+          echo "Graphviz installed successfully"
+
+  via_action_no_update_and_mandb:
+    runs-on: ubuntu-24.04
+
+    steps:
+      - name: Disable man-db triggers
+        run: |
+          sudo dpkg-divert --local --rename --add /usr/bin/mandb
+          sudo ln -s /bin/true /usr/bin/mandb
+
+      - name: Install Graphviz via action
+        uses: ts-graphviz/setup-graphviz@v2
+        with:
+          ubuntu-skip-apt-update: true
+
+      - name: Verify Graphviz installation
+        run: |
+          dot -vV
+          if ! command -v dot &> /dev/null; then
+            echo "Graphviz installation failed"
+            exit 1
+          fi
+          echo "Graphviz installed successfully"
+
+        
   via_apt_install:
     runs-on: ubuntu-24.04
     steps:
